version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "finances_db"
      POSTGRES_USER: "finances_db_user"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
